[package]
name = "cpu"
version = "0.1.0"
authors = ["araneavalon <35237939+araneavalon@users.noreply.github.com>"]
edition = "2018"

[dependencies]
assembler = { path = "assembler" }
sdl2 = "0.32.1"
clap = "2.33.0"
